### ISSUE TITLE
Remove category "Language Packs"

### ISSUE THREAD

**Issue by gregvanl** [ZainChen/omi-vscode#1]
The category "Language Packs" is for extensions that provide localized display languages such as German and Japanese.

![image](https://user-images.githubusercontent.com/12818376/55659887-7597ea80-57b8-11e9-85b4-44f80d89c44b.png)

**Comment by ZainChen** [comment]
Hello, it has been deleted.^_^

**Comment by ZainChen** [comment]
You are my first issue, very happy.
![image](https://user-images.githubusercontent.com/15615524/55891652-85179900-5be7-11e9-9deb-a0d8d77a0541.png)

**Comment by gregvanl** [comment]
@ZainChen Thank you for fixing this so quickly!
