### ISSUE TITLE
Overuse of categories and tags

### ISSUE THREAD

**Issue by chrisdias** [ZainChen/omi-vscode#2]
This extension declares every available category even though they don't apply:

![image](https://user-images.githubusercontent.com/1487073/58386113-f2bd3000-7faf-11e9-8afc-ae66841bc5ef.png)

For example, you say that it is a `Debugger`, but you don't contribute a debugger in `package.json`.

Please reduce the number of categories to what the extension supports.  

Similarly, the extension declares a large number of tags, this should be reduced to what is necessary. 

The reason for this is to make search more accurate in the marketplace, otherwise searching for a Tag or Category becomes useless if all extensions show up, regardless of what they provide.

**Comment by ZainChen** [comment]
![image](https://user-images.githubusercontent.com/15615524/58393968-aaffdc80-8073-11e9-893a-202245fa36b6.png)

**Comment by chrisdias** [comment]
Hi -

Here's the categories I would *delete*:

* themes
* linters
* debuggers
* other
* keymaps
* Extension Packs
* SCM providers
* Azure

Your extension does not fall into any of these categories if I understand correctly.

I can make a PR if you would like.

**Comment by ZainChen** [comment]
Hi, very happy that you can PR.
![image](https://user-images.githubusercontent.com/15615524/58413749-241b2600-80ac-11e9-93d4-833ff595c533.png)
Sorry, it will bring you trouble, thank you!

**Comment by ZainChen** [comment]
Hello, I changed the categories. Hope to keep these related categories: themes, other, keys, Extension Packs. thank you!
![image](https://user-images.githubusercontent.com/15615524/59326083-f377f500-8d17-11e9-904e-fdc832c1a710.png)
